version: 0.96.0

v: true
d: true

# Tắt lấy client ID từ certificate
tls_client_id_from_cert: false
# Đặt client ID tĩnh
client_id: "client1"

redis_db_keys: 1
redis_host_port: "127.0.0.1:6379"

db_host: "10.0.2.147"
db_port: 5432
postgresql_enable: true

keystore_cache_on_start_enable: false
keys-dir: ".acrakeys"  # Sử dụng đường dẫn tương đối

# log config
log_to_console: true
log_to_file: "/home/hytong/NT534-Database-Security-Suite/acra/acra_server.log"

# encryption and masking
encryptor_config_file: "/home/hytong/NT534-Database-Security-Suite/acra/config/encryptor_config.yaml"

# tls config
tls_auth: 4
tls_key: "/home/hytong/NT534-Database-Security-Suite/acra/acra_tls_certs/acraserver.key.pem"
tls_cert: "/home/hytong/NT534-Database-Security-Suite/acra/acra_tls_certs/acraserver.crt.pem"
tls_ca: "/home/hytong/NT534-Database-Security-Suite/acra/acra_tls_certs/ca.crt.pem"

# Prometheus setting
incoming_connection_prometheus_metrics_string: "http://127.0.0.1:8000"