version: 0.96.0

v: true
d: true

tls_client_id_from_cert: true
#client_id: "acra_app"
#client_id: "20fb42c517922eb023a8bf52674ee7b5f53c4d6ed48d838966b8bdc09737191678aab90f7f3169f07365f32082af230ef87da5ac4b4e8b9c189b4b9fd280d291"

redis_db_keys: 1
redis_host_port: "127.0.0.1:6379"

db_host: "10.0.2.147"
db_port: 5432
postgresql_enable: true

keystore_cache_on_start_enable: false
keys-dir: "/home/hytong/acra/.acrakeys/"

# log config
log_to_console: true
log_to_file: "acra_server.log"

# encryption and masking
encryptor_config_file: "config/encryptor_config.yaml"

# tls config
tls_auth: 4
tls_key: "acra_tls_certs/acraserver.key.pem"
tls_cert: "acra_tls_certs/acraserver.crt.pem"
tls_ca: "acra_tls_certs/ca.crt.pem"

# Prometheus setting
incoming_connection_prometheus_metrics_string: "http://127.0.0.1:8000"
