version: 0.96.0
defaults:
  crypto_envelope: acrablock
  transparent_encryption: true
schemas:
  - table: "users"
    columns:
      - "user_id"
      - "username"
      - "email"
      - "password_hash"
      - "full_name"
      - "address"
      - "phone_number"
      - "created_at"
    encrypted:
      - column: "email"
        masking: "***@placeholder.com"
        plaintext_length: 0
        plaintext_side: left
      - column: "phone_number"
        masking: "+XX XXX XXX "
        plaintext_length: 4
        plaintext_side: right
  - table: "orders"
    encrypted: []
  - table: "order_details"
    encrypted: []
  - table: "products"
    encrypted: []